2020-10-22 20:41:09,652 [main.py:150] <module> [ERROR] Error reading input file delimeter from config. Using WebLog default of ,%,
2020-10-22 20:41:09,654 [main.py:362] <module> [INFO] An error has occurred. Attempting to recover...
2020-10-22 20:42:20,531 [main.py:55] <module> [DEBUG] IP address, 127.0.0.1, read from config.
2020-10-22 20:42:20,531 [main.py:61] <module> [DEBUG] Successfully validated 127.0.0.1.
2020-10-22 20:42:20,532 [main.py:69] <module> [DEBUG] UDP port, 2002, read from config.
2020-10-22 20:42:20,532 [main.py:77] <module> [DEBUG] Successfully validated 2002.
2020-10-22 20:42:20,532 [main.py:88] <module> [DEBUG] DCL command string, MAKELOG+HTML, read from config.
2020-10-22 20:42:20,535 [main.py:96] <module> [DEBUG] FTP Uploads True
2020-10-22 20:42:20,535 [main.py:104] <module> [DEBUG] Server URL, ftp.azureradio.com, read from config.
2020-10-22 20:42:20,535 [main.py:113] <module> [DEBUG] FTP Username, user read from config.
2020-10-22 20:42:20,535 [main.py:122] <module> [DEBUG] FTP Password read from config.
2020-10-22 20:42:20,535 [main.py:131] <module> [DEBUG] REP Input File, E:\DAD\Files\PLIST.REP, read from config.
2020-10-22 20:42:20,535 [main.py:139] <module> [DEBUG] HTML output file and path, index.html, read from config.
2020-10-22 20:42:20,536 [main.py:150] <module> [ERROR] Error reading input file delimeter from config. Using WebLog default of ,%,
2020-10-22 20:42:20,536 [main.py:155] <module> [DEBUG] Playlist hour string, 09, 10, 11, 12, 13, read from config.
2020-10-22 20:42:20,537 [main.py:163] <module> [DEBUG] Hours configured are ['09', ' 10', ' 11', ' 12', ' 13'].
2020-10-22 20:42:20,537 [main.py:174] <module> [DEBUG] Read highlight keyword, Highlight_String, from config.
2020-10-22 20:42:20,538 [main.py:182] <module> [DEBUG] Playlist title, ENCO WebLog, read from config.
2020-10-22 20:42:20,538 [main.py:190] <module> [DEBUG] Playlist subtitle, WebLog by D.I. Aspinwall, read from config.
2020-10-22 20:42:20,539 [main.py:200] <module> [DEBUG] Read highlight color, 00af00, from config.
2020-10-22 20:42:20,540 [main.py:362] <module> [INFO] An error has occurred. Attempting to recover...
